learning_objectives.md

add first draft of independent learning objectives

---

.github/workflows/build-and-deploy.yml
DESCRIPTION
Rmd/introduction.Rmd

The idea for this is a self-coding session at the end of the first session ("R and statistical concepts used").
It includes a suggested teaching method for the rest of the course:
1. simulation (what process generates the kind of data I see)
2. initial estimation (using the simulation function to conduct inference)
3. full estimation (with stan)
4. open-source packages (what's out there to do this work)
step (2) might turn out not to be needed but is there to smooth the transition to stan.
Review on this PR please on (1) the general setup and (2) any errors/typos etc. More substantial changes to this session (which may well be needed/sensible) would be better in a separate PR, I think.

introduction session

---

sessions.qmd

update session times

---

sessions/00-introduction-and-course-overview.qmd
sessions/01-R-Stan-and-statistical-concepts.qmd
sessions/02-delay-distributions.qmd
sessions/03-biases-in-delay-distributions.qmd
sessions/04-using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd
sessions/06-nowcasting.qmd
sessions/07-forecasting-concepts.qmd
sessions/08-forecasting-models.qmd
sessions/09-ensemble-modelling.qmd
sessions/10-methods-in-the-real-world.qmd
sessions/11-from-line-list-to-estimates.qmd
sessions/12-overview-of-available-tools.qmd
sessions/13-end-of-course-summary-and-discussion.qmd

Adds remaining template text and aims to include info from the session overview into all the individual sessions

Add remaining skeleton

---

sessions.qmd
sessions/01-R-Stan-and-statistical-concepts.qmd
sessions/02-delay-distributions.qmd
sessions/03-biases-in-delay-distributions.qmd
snippets/onset-hosp.r

Brings the sessions in line with the plan.

restructure first 3 sessions

---

.github/workflows/deploy.yaml
sessions/00-introduction-and-course-overview.qmd
sessions/slides/introduction-to-the-course-and-the-instructors.qmd

Closes #55 
Using the reveal js engine for simple slides like these (and possibly would make sense to use for all).

Intro slides

---

sessions/R-estimation-and-the-renewal-equation.qmd
sessions/slides/introduction-to-reproduction-number.qmd

First draft of R slides
Closes #64.

reproduction number slides

---

sessions/slides/convolutions.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

Closes #63 
Might also help towards #81

first draft of convolution slides

---

stan/estimate-inf-and-r.stan

Update estimate-inf-and-r.stan to fit to onsets

---

sessions/slides/forecasting-as-an-epidemiological-problem.qmd

Closes #68 
Wrote these earlier but will stop here as this will build on #49.

forecasting intro slides

---

.github/workflows/deploy.yaml

This adds the website as artifact to all PRs. should make reviewing a bit nicer and less error prone as can see a previous of the course at all times without a local check out.

Website as artifact

---

DESCRIPTION
getting-set-up.qmd

I decided to switch to working with Rstudio this week to get the participant experience. Did the getting set up workflow and made some corrections. 
Made the choice to switch to `pak` as may save some issues with people getting setup.

Fixes getting setup

---

sessions/R-estimation-and-the-renewal-equation.qmd

sample onsets in renewal session

---

getting-set-up.qmd

upgrade dependencies

---

getting-set-up.qmd
sessions/R-Stan-and-statistical-concepts.qmd
sessions/R-estimation-and-the-renewal-equation.qmd
sessions/biases-in-delay-distributions.qmd
sessions/delay-distributions.qmd
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd
sessions/nowcasting.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

update recommendation on Visual editor

---

sessions/slides/introduction-to-statistical-concepts.qmd

switch x/y axis labels on temperature/PDF plot

intro to statistical concepts - quick fix

---

sessions/R-Stan-and-statistical-concepts.qmd
sessions/slides/introduction-to-stan.qmd
stan/coin.stan

introduction to stan

---

stan/estimate-inf-and-r-rw.stan
stan/joint-nowcast-with-r.stan

Based on @sbfnk investigation in #132 this PR adds light constraints to `init_R`
Closes #131

Add light init_R constraints

---

sessions/introduction-and-course-overview.qmd

I think it would be good to have a bit of text on the overview page, mainly for future/remote use of the course.
I've copied text out from the intro slides for this.
I've also added a bit of a blurb to introduce and motivate the initial focus on delays (which IMO is the least "obvious" aspect of the course). Changes welcome.

Update course overview page / add motivational blurb

---

sessions/delay-distributions.qmd
snippets/onset-hosp.r

This PR:
- fixes some sentence structures,
- formats a section with line breaks,
- fixes an instance of partial matching,
- Improves a plot by removing the negative x-axis breaks, and
- makes a code block more readable by removing repeated code.

Review of session on delay distributions

---

sessions/delay-distributions.qmd
snippets/onset-hosp.r

- Adds motivating introduction - #144
- Removes coding exercises - #165
Other fixes
- Adds headers and a bit of clarifying text
- Adds comments to the `onset-hosp.R` snippet to clarify what's going on there
This crossed with @jamesmbaazam review in the meantime but attempted to merge the two. I'll take a break and come back in a bit so we don't cross again!

Delays session - add introduction & remove coding exercises

---

DESCRIPTION

Closes #135 and updates the author list. Removed the `cph` as I don't think its accurate?

Suggests to depends

---

sessions/R-estimation-and-the-renewal-equation.qmd

Closes #186 
I did a search everywhere and read through all onset uses. This is the only one I saw.

Check noisy and integer onsets used everywhere

---

sessions/forecasting-concepts.qmd

Move proper scoring rules tip

---

sessions/introduction-and-course-overview.qmd

minor edits to intro

---

sessions/nowcasting.qmd
sessions/slides/introduction-to-joint-estimation-of-nowcasting-and-reporting-delays.qmd
sessions/slides/introduction-to-nowcasting.qmd

implements suggestions in #211 
See there for more comments / questions.

apply review suggetions

---

sessions/R-Stan-and-statistical-concepts.qmd
sessions/R-estimation-and-the-renewal-equation.qmd
sessions/biases-in-delay-distributions.qmd
sessions/delay-distributions.qmd
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd
sessions/joint-nowcasting.qmd
sessions/nowcasting.qmd
sessions/slides/introduction-to-stan.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

Closes #159 
Closes #36 
This required quite a bit of copying & pasting which is not ideal - does visual editor deal well with knitting chunks specified in separate files? If yes these would be a good option.

update intro sections

---

sessions/biases-in-delay-distributions.qmd

in the bias section.
Closes #82

introduce double interval censoring

---

sessions/biases-in-delay-distributions.qmd

with a bit more data the estimate is spot on
Closes #77

estimate bias later

---

sessions/delay-distributions.qmd
sessions/forecasting-concepts.qmd
sessions/nowcasting.qmd

Standardise cutoffs & outbreak size

---

sessions/slides/convolutions.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

as discussed in comments there

minor edits to convolution review

---

sessions/forecasting-models.qmd

The session looks great to me. This is just catching typos and removing the repeated set.seed (closes #218).

Review forecasting models session

---

data-raw/generate-example-forecasts.r
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd

Use onset df from a snippet everywhere

---

sessions/slides/convolutions.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

Closes #81. 
I also added some more correct maths for double interval censoring. I agree it is a bit scary but also think better than hand waving away the issue?

Review convolution session

---

sessions/delay-distributions.qmd
sessions/forecasting-concepts.qmd
sessions/introduction-and-course-overview.qmd
sessions/joint-nowcasting.qmd
sessions/nowcasting.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

Closes #233. 
I search for .qmd and fixed everything I saw

Issue 233: fix qmd links

---

sessions/introduction-and-course-overview.qmd

Add a section on what to expect in each session

---

sessions/end-of-course-summary-and-discussion.qmd

At some point we might want to add why we chose these but for now I think this is good.
Closes #246 
Closes #245

More further reading

---

sessions/R-estimation-and-the-renewal-equation.qmd
sessions/slides/introduction-to-reproduction-number.qmd

closes #239 
done via repo search for $R$ which hopefully caught all

replace $R$ with $R_t$

---

sessions/R-Stan-and-statistical-concepts.qmd

stan clarifications

---

sessions/slides/introduction-to-biases-in-epidemiological-delays.qmd

edits to bias delay slides

---

sessions/R-estimation-and-the-renewal-equation.qmd
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd
sessions/joint-nowcasting.qmd
sessions/nowcasting.qmd

for consistency - as we're loading the package anyway it should be fine

use unqualified `here()` everywhere

---

sessions/R-estimation-and-the-renewal-equation.qmd

closes #229 thanks to [suggestion](https://github.com/nfidd/nfidd/issues/229#issuecomment-2185262925)

Add init function to model 2 in renewal session

---

sessions/R-Stan-and-statistical-concepts.qmd
sessions/R-estimation-and-the-renewal-equation.qmd
sessions/biases-in-delay-distributions.qmd
sessions/delay-distributions.qmd
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd
sessions/joint-nowcasting.qmd
sessions/nowcasting.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

add snippet for file locations

---

sessions/forecasting-concepts.qmd

add forecast intro blurb

---

sessions/joint-nowcasting.qmd

add note to joint nowcasting model

---

stan/estimate-inf-and-r-rw.stan
stan/joint-nowcast-with-r.stan
stan/statistical-r.stan

Issue 234: Remove all bounds on init_R and remove upper boound on rw_sd

---

functions/geometric-diff-ar.r
functions/geometric-random-walk.r
sessions/R-estimation-and-the-renewal-equation.qmd
sessions/forecasting-models.qmd

adds R functions for the geometric random walks
@seabbs if you don't like this in the forecasting session I can take it out again
Closes #122

Geometric rw functions

---

sessions/R-estimation-and-the-renewal-equation.qmd

addresses https://github.com/nfidd/nfidd/pull/279#issuecomment-2185321752

add text about setting initial init_R

---

sessions/R-estimation-and-the-renewal-equation.qmd

thicker line in plot

---

sessions/forecasting-models.qmd

forecasting models review

---

sessions/slides/forecasting-as-an-epidemiological-problem.qmd
sessions/slides/forecasting-models.qmd
sessions/slides/introduction-to-joint-estimation-of-nowcasting-and-reporting-delays.qmd
sessions/slides/introduction-to-nowcasting.qmd

bringing everything in line with the course visual identity

same structure for final slides

---

sessions/R-Stan-and-statistical-concepts.qmd

we don't have those arguments any more

remove statement about output

---

sessions/nowcasting.qmd

Small text fixes, up to where we start to fit models
Overlaps with #304

Nowcasting - typos and echo snippet

---

sessions/slides/forecasting-as-an-epidemiological-problem.qmd

Minor clarifications / highlighting / consistency changes

Update forecasting concepts slides

---

sessions/overview-of-available-tools.qmd

remove notes on which models packages relate to (so course participants have a chance to think about it)

update tools session

---

sessions.qmd

another sessions update

---

sessions/examples-of-available-tools.qmd
sessions/slides/tools.qmd

Tool session update

---

sessions/end-of-course-summary-and-discussion.qmd

add text to references

---

index.qmd

- Links to discussion board
- Links to issues
- Slight text rearrangement

Link discussion board on site index

---

DESCRIPTION
README.Rmd
getting-set-up.qmd

nfiidd -> nfidd

---

.github/workflows/render-readme.yaml

fixes #343 (or at least in my experience it does)

don't check URLs

---

.github/workflows/deploy.yaml

With this we can enable the merge queue, which should make simultaneous work on this (slightly) smoother.

update actions for merge queue

---

getting-set-up.qmd
sessions/R-Stan-and-statistical-concepts.qmd
sessions/R-estimation-and-the-renewal-equation.qmd
sessions/biases-in-delay-distributions.qmd
sessions/delay-distributions.qmd
sessions/forecast-ensembles.qmd
sessions/forecasting-concepts.qmd
sessions/forecasting-models.qmd
sessions/joint-nowcasting.qmd
sessions/methods-in-the-real-world.qmd
sessions/nowcasting.qmd
sessions/using-delay-distributions-to-model-the-data-generating-process-of-an-epidemic.qmd

- some clarification of code snippets vs functinos
- some typo fixing
- some linting
- updates library blurbs
- updates intro to make installation instructions more prominent
- removes library calls do `cmdstanr` package as it's not used explicitly anywhere

Full review of sessions

---

getting-set-up.qmd

clarify copy & paste option

---

DESCRIPTION
sessions/forecast-ensembles.qmd

I think it makes a nice addition for the "full" version but it makes an already quite complicated session even more complicated. Perhaps something we want to cut again when thinking about this for a 60 minute session.

add mixture ensembles

---

DESCRIPTION

bump scoringutils to CRAN version

---

.github/workflows/deploy.yaml
.github/workflows/render-readme.yaml
DESCRIPTION
sessions/forecast-ensembles.qmd

use epiforecasts universe instead of github

---

R/add_delays.r
R/geometric-diff-ar.r
R/nfidd-stan-tools.r
man/add_delays.Rd
man/geometric_diff_ar.Rd
man/nfidd_cmdstan_model.Rd
man/nfidd_stan_models.Rd

causing build failure on the universe

fix package examples

---

sessions/forecast-ensembles.qmd
sessions/slides/introduction-to-ensembles.qmd

I added the `stackr` stuff after IDM so this is not actually present there. I think it's interesting but probably too much. Also if using we should resolve https://github.com/epiforecasts/stackr/issues/4

bring in IDM changes to ensemble session

---

sessions/forecast-evaluation.qmd
sessions/forecast-visualisation.qmd
sessions/nfidd.bib
sessions/slides/forecast-evaluation.qmd
sessions/slides/forecasting-as-an-epidemiological-problem.qmd

- this also brings in the `bib` file from IDM
- haven't actually tried rendering yet but will CI have a look
- I presume decimal `order` in the YAML header is OK but if not will have to re-order

split forecasting concepts and bring in IDM update

---

inst/stan/estimate-inf-and-r-rw-forecast.stan
inst/stan/estimate-inf-and-r-rw.stan
inst/stan/joint-nowcast-with-r.stan
inst/stan/statistical-r.stan

write the zero for <1 decimals

---

reference/learning_objectives.qmd
reference/sessions.qmd

split session 8

---

sessions/R-Stan-and-statistical-concepts.qmd

fix session 1 wrap up

---

sessions/slides/introduction-to-nowcasting.qmd

fix #317 - add arrows graphic to nowcasting slides

---

sessions/forecast-ensembles.qmd

session-9-going-further

---

sessions/joint-nowcasting.qmd

session-6.5-going-further

---

sessions/nowcasting.qmd

session-6-going-further

---

reference/sessions.qmd
sessions/forecasting-concepts.qmd
sessions/slides/introduction-to-forecasting.qmd

update session titles

---

sessions/introduction-and-course-overview.qmd
sessions/slides/from-line-list-to-decisions.qmd

tweak language around generative models

---

sessions/delay-distributions.qmd
sessions/introduction-and-course-overview.qmd

I couldn't get the delay distributions footnote to render so have switched to inline notes which seem easier to handle anyway and render fine.

fix footnotes

---

reference/sessions.qmd

add ../ to all links to account for folder move

---

sessions/forecasting-models.qmd

format in line with other sessions

forecasting models -  break up going further section
